### ISSUE TITLE
Various missing properties referenced on object returned from Moltin api

### ISSUE THREAD

**Issue by timhere** [moltin/vue-demo-store#1]
I received this console error after trying to load the app:

`[Vue warn]: Error in render: "TypeError: Cannot read property 'with_tax' of undefined"`

After inspecting the data returned from the api, the `display_tax` property does not exist. The Moltin api seems to use URL versioning: the request goes to `https://api.moltin.com/v2/products`. I assume a property was changed/removed which causes this error.

Removing line 21 of the `Home.vue` component:
`<p>{{ product.meta.display_price.with_tax.formatted }}</p>`
and line 10 of the `Products.vue` component:
`<p class="price">{{ product.data[0].meta.display_price.with_tax.formatted }}</p>`
allows the pages to render.

On the product page I saw this error in the console:
`[Vue warn]: Error in render: "TypeError: Cannot read property 'files' of undefined"`

It appears that there have been multiple changes to the structure of the object returned from the api request.

**Comment by Jmz** [comment]
Hey @timhere 

We only return the `display_price` property for a product if the product has a price in the requested currency. Some naughty person had changed the currency for our demo store so the price wasn't defined. I've changed that back so the app should be running again now.

Thanks!

**Comment by notrab** [comment]
I can confirm this works so I’m going to close this. Feel free to open another issue or respond if you’re still seeing issues.
